#!/usr/bin/env python3
"""Fetch meetup events from a public ICS feed and write data/meetups.yaml for Hugo."""

from __future__ import annotations

import argparse
import os
import re
import sys
from datetime import date, datetime, timezone
from html import unescape
from pathlib import Path
from typing import Any

import requests
import yaml
from icalendar import Calendar

ROOT = Path(__file__).resolve().parent.parent
OUT_PATH = ROOT / "data" / "meetups.yaml"

TAG_RE = re.compile(r"<[^>]+>")
URL_RE = re.compile(r"https?://[^\s<>\"']+", re.IGNORECASE)
SPEAKER_RE = re.compile(r"^\s*speaker\s*:\s*(.+?)\s*$", re.IGNORECASE | re.MULTILINE)


def strip_html(text: str) -> str:
    if not text:
        return ""
    text = unescape(text)
    text = TAG_RE.sub(" ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text


def to_iso(dt: date | datetime) -> str:
    if isinstance(dt, date) and not isinstance(dt, datetime):
        dt = datetime.combine(dt, datetime.min.time(), tzinfo=timezone.utc)
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    return dt.astimezone(timezone.utc).isoformat().replace("+00:00", "Z")


def extract_link(description: str, location: str) -> str | None:
    for blob in (location or "", description or ""):
        blob = blob.strip()
        if blob.lower().startswith(("http://", "https://")):
            return blob.split()[0]
        match = URL_RE.search(blob)
        if match:
            return match.group(0).rstrip(".,)")
    return None


def extract_speaker(title: str, description: str) -> str | None:
    match = SPEAKER_RE.search(description or "")
    if match:
        return match.group(1).strip()
    if " - " in title:
        left = title.split(" - ", 1)[0].strip()
        if left and len(left) < 120:
            return left
    return None


def parse_events(ics_bytes: bytes) -> list[dict[str, Any]]:
    cal = Calendar.from_ical(ics_bytes)
    events: list[dict[str, Any]] = []

    for component in cal.walk("VEVENT"):
        uid = str(component.get("UID", "")).strip()
        summary = str(component.get("SUMMARY", "")).strip() or "Meetup"
        dtstart = component.get("DTSTART")
        dtend = component.get("DTEND")
        if not dtstart:
            continue

        start = dtstart.dt
        end = dtend.dt if dtend else start
        if isinstance(start, date) and not isinstance(start, datetime):
            # All-day event: treat end as end of that day
            if isinstance(end, date) and not isinstance(end, datetime):
                end = datetime.combine(end, datetime.max.time(), tzinfo=timezone.utc)
            start = datetime.combine(start, datetime.min.time(), tzinfo=timezone.utc)
        if isinstance(end, date) and not isinstance(end, datetime):
            end = datetime.combine(end, datetime.max.time(), tzinfo=timezone.utc)

        location = str(component.get("LOCATION", "") or "").strip()
        raw_desc = str(component.get("DESCRIPTION", "") or "")
        description = strip_html(raw_desc)
        link = extract_link(raw_desc, location)
        speaker = extract_speaker(summary, raw_desc)

        # Skip very old cancelled-looking junk without uid
        if not uid:
            uid = f"{summary}-{to_iso(start)}"

        event: dict[str, Any] = {
            "uid": uid,
            "title": summary,
            "start": to_iso(start),
            "end": to_iso(end),
        }
        if location:
            event["location"] = location
        if description:
            event["description"] = description
        if link:
            event["link"] = link
        if speaker:
            event["speaker"] = speaker

        events.append(event)

    # Deduplicate by uid (keep latest end)
    by_uid: dict[str, dict[str, Any]] = {}
    for ev in events:
        key = ev["uid"]
        if key not in by_uid or ev["end"] > by_uid[key]["end"]:
            by_uid[key] = ev

    events = list(by_uid.values())
    events.sort(key=lambda e: e["start"])
    return events


def write_yaml(events: list[dict[str, Any]], ics_url: str | None) -> None:
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "updated": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "ics_url": ics_url or "",
        "events": events,
    }
    header = (
        "# Generated by scripts/sync-meetup-calendar.py - do not edit by hand.\n"
        "# Re-run locally or wait for the sync-meetups GitHub Action.\n"
    )
    OUT_PATH.write_text(
        header + yaml.safe_dump(payload, sort_keys=False, allow_unicode=True),
        encoding="utf-8",
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--ics-url",
        default=os.environ.get("MEETUP_CALENDAR_ICS_URL", "").strip(),
        help="Public ICS URL (or set MEETUP_CALENDAR_ICS_URL)",
    )
    args = parser.parse_args()

    if not args.ics_url:
        print(
            "MEETUP_CALENDAR_ICS_URL not set; writing empty events list.",
            file=sys.stderr,
        )
        write_yaml([], None)
        return 0

    print(f"Fetching {args.ics_url}", file=sys.stderr)
    resp = requests.get(args.ics_url, timeout=60)
    resp.raise_for_status()
    events = parse_events(resp.content)
    print(f"Parsed {len(events)} events", file=sys.stderr)
    write_yaml(events, args.ics_url)
    print(f"Wrote {OUT_PATH}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
